server:
  port: 8081

spring:
  username: sa
  password: password
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:costTestDB


  #  datasource:
  #   driverClassName: org.h2.Driver

  r2dbc:
    url: r2dbc:h2:mem:costTestDB
    username: sa
    password: password
#    initialization-mode: always


clients:
  binList:
    url: "https://lookup.binlist.net"